### PR TITLE
add iosxr commit parser, fix init.yml

### PR DESCRIPTION
**Pull request by wasabi222**
let me know if this format works for this tag and I'll start to write some more for iosxr. 

The `init` file was previously matching on an extra space for the hostnameprefix, and cisco adds the ` : ` after the tag match as well.

### CODE REVIEW

**Comment by wasabi222** [comment]
Upon further review, I see that the line won't parse with that extra space if the hostnameprefix is missing. I added a separate line for the hostnameprefix, otherwise leaving the prefix as optional, while it parses in one line, leaves an extra space in the hostname (eg. hostname: 'xrv '). This `init.yml` should match on either.

**Comment by loverend** [comment]
Thanks for the updated `init.yml`. You will need to add a new file under `napalm_logs/config/iosxr` for the specific error. I only see the tests for the error included in the commits.

**Comment by wasabi222** [comment]
haha whoops. Added @loverend

**Comment by loverend** [comment]
This is really great, thanks. I was surprised to see that there is no relevant model in openconfig for configuration.

Because of the hostname fix some the iosxr tests are failing. Could you please update the `yang.json` file for each test in `tests/config/iosxr/` and remove the space after the device name. Hopefully then the checks will all pass.

**Comment by wasabi222** [comment]
hmm done but checks still appear to be failing :/

**Comment by loverend** [comment]
Ah you will also need to remove the `: ` from `message` in each of the `yang.json` files. There is also another instance of `host` in there.

Here is the diff, please apply this and hopefully all should then pass:

```
diff --git a/tests/config/iosxr/BGP_PREFIX_THRESH_EXCEEDED/default_v4/yang.json b/tests/config/iosxr/BGP_PREFIX_THRESH_EXCEEDED/default_v4/yang.json
index f86c6b6..5904ad7 100644
--- a/tests/config/iosxr/BGP_PREFIX_THRESH_EXCEEDED/default_v4/yang.json
+++ b/tests/config/iosxr/BGP_PREFIX_THRESH_EXCEEDED/default_v4/yang.json
@@ -35,12 +35,12 @@
     "pri": "149",
     "nodeId": "RP/0/RSP1/CPU0",
     "processName": "bgp",
-    "host": "vmx01 ",
+    "host": "vmx01",
     "tag": "ROUTING-BGP-5-MAXPFX",
     "messageId": "2647599",
     "date": "Mar 28",
     "timeZone": "UTC",
-    "message": ": No. of IPv4 Unicast prefixes received from 1.2.3.4 has reached 94106, max 125000",
+    "message": "No. of IPv4 Unicast prefixes received from 1.2.3.4 has reached 94106, max 125000",
     "milliseconds": ".941"
   },
   "timestamp": 1490713710,
diff --git a/tests/config/iosxr/BGP_PREFIX_THRESH_EXCEEDED/default_v6/yang.json b/tests/config/iosxr/BGP_PREFIX_THRESH_EXCEEDED/default_v6/yang.json
index 9981c59..f1414c0 100644
--- a/tests/config/iosxr/BGP_PREFIX_THRESH_EXCEEDED/default_v6/yang.json
+++ b/tests/config/iosxr/BGP_PREFIX_THRESH_EXCEEDED/default_v6/yang.json
@@ -35,12 +35,12 @@
     "pri": "149",
     "nodeId": "RP/0/RSP1/CPU0",
     "processName": "bgp",
-    "host": "vmx01 ",
+    "host": "vmx01",
     "tag": "ROUTING-BGP-5-MAXPFX",
     "messageId": "2647599",
     "date": "Mar 28",
     "timeZone": "UTC",
-    "message": ": No. of IPv6 Unicast prefixes received from fc00::1001 has reached 94106, max 125000",
+    "message": "No. of IPv6 Unicast prefixes received from fc00::1001 has reached 94106, max 125000",
     "milliseconds": ".941"
   },
   "timestamp": 1490713710,
diff --git a/tests/config/iosxr/NTP_SERVER_UNREACHABLE/default/yang.json b/tests/config/iosxr/NTP_SERVER_UNREACHABLE/default/yang.json
index f99c415..37f42f9 100644
--- a/tests/config/iosxr/NTP_SERVER_UNREACHABLE/default/yang.json
+++ b/tests/config/iosxr/NTP_SERVER_UNREACHABLE/default/yang.json
@@ -13,9 +13,9 @@
     "tag": "IP-IP_NTP-5-SYNC_LOSS",
     "date": "Aug 21",
     "processId": "262",
-    "message": ": Synchronization lost : 172.17.17.1 : The association was removed",
+    "message": "Synchronization lost : 172.17.17.1 : The association was removed",
     "severity": 3,
-    "host": "device3 ",
+    "host": "device3",
     "facility": 12
   },
   "timestamp": 1503308354,
```

**Comment by loverend** [comment]
Thanks @wasabi222

**Pull request merged**
