### PR TITLE
Added messages for user enter,  exit, and writing from config mode.

### PR DESCRIPTION
**Pull request by bigpick**
Three new syslog message configs for EOS:
 * User enter configuration mode 
      ```
      switch> enable
      switch# config
      switch(config)# 
      ```
 * User write in configuration mode 
      ```
      switch> enable
      switch# config
      switch(config)# write
      ```
 * User exit configuration mode 
      ```
      switch> enable
      switch# config
      switch(config)# exit
      switch#
      ```

### CODE REVIEW

**Comment by bigpick** [comment]
Updated `test/config/eos/` with the three additional cases.

**Comment by luke-orden** [comment]
The tests are failing - https://travis-ci.org/napalm-automation/napalm-logs/jobs/444641566

Please let me know if you need any help correcting these.

**Comment by bigpick** [comment]
Hm, @luke-orden, let me try fixing that up. Looks like it's the IP address that needs to be changed to mirror the localhost test in Travis.

Also, not quite sure why my struct's have a '_stamp' in them, but not in the Travis generated model?

**Comment by luke-orden** [comment]
Where did you get the `_stamp` from? I don't see this when testing myself.

**Comment by bigpick** [comment]
The `_stamp` is just automatically one of the fields in the returned object seen on the event bus.

If I do a `test.ping`, it's also there too. On the event bus:
**test.ping**
```
salt/job/20181023073018797854/ret/GeorgeSwitch	{
    "_stamp": "2018-10-23T11:30:18.899332", 
    "cmd": "_return", 
    "fun": "test.ping", 
    "fun_args": [], 
    "id": "GeorgeSwitch", 
    "jid": "20181023073018797854", 
    "retcode": 0, 
    "return": true, 
    "success": true
}
```

**user_exit_config_mode**
```
napalm/syslog/eos/API_EXIT_CONFIG_MODE/GeorgeSwitch	{
    "_stamp": "2018-10-23T11:27:41.669939", 
    "error": "API_EXIT_CONFIG_MODE", 
    "facility": 20, 
    "host": "GeorgeSwitch", 
    "ip": "172.16.0.2", 
    "message_details": {
        "date": "Oct 23", 
        "facility": 20, 
        "host": "GeorgeSwitch", 
        "message": ": User local_command_api exited configuration session napalm_404112 on command-api (unix:)", 
        "pri": "165", 
        "processName": "ConfigAgent", 
        "severity": 5, 
        "tag": "SYS-5-CONFIG_SESSION_EXITED", 
        "time": "11:28:08"
    }, 
    "os": "eos", 
    "severity": 5, 
    "timestamp": 1540294088, 
    "yang_message": {
        "users": {
            "user": {
                "local_command_api": {
                    "action": {
                        "api_exit_config_mode": true
                    }
                }
            }
        }
    }, 
    "yang_model": "NO_MODEL"
}
```

**Comment by luke-orden** [comment]
The `_stamp` key is added by Salt. If you want to see exactly what is output by napalm-logs you can use one of the example clients under https://github.com/napalm-automation/napalm-logs/tree/develop/examples

**Comment by luke-orden** [comment]
Thanks

**Pull request merged**
